movies:
    screens:  
      -   title: Turning Red
          description: About Turning Red movie
          runningTime: 85
          ticketPrice: 11
          specialCode: 0 
          movieSequence: 
            - 1
            - 4
            - 7
          movieTimings: 
            - 0900
            - 1430
            - 1930
      -   title: Spider-Man NoWay Home
          description: Spider-Man NoWay Home
          runningTime: 90
          ticketPrice: 12.5
          specialCode: 1 
          movieSequence: 
            - 2
            - 5
            - 8
          movieTimings: 
            - 1100
            - 1610
            - 2110
      -   title: The Batman
          description: About Bat Man adventure
          runningTime: 95
          ticketPrice: 9
          specialCode: 0
          movieSequence: 
            - 3
            - 6
            - 9
          movieTimings: 
            - 1250
            - 1750
            - 2300       