movies:
    screens:  
      -   title: Turning Red
          description: About Turning Red movie
          runningTime: 125
          ticketPrice: 11
          specialCode: 0 
          movieSequence: 
            - 1
            - 4
            - 7
          movieTimings: 
            - '09:00'
            - '14:30'
            - '19:30'
      -   title: Spider-Man NoWay Home
          description: Spider-Man NoWay Home
          runningTime: 90
          ticketPrice: 12.5
          specialCode: 1 
          movieSequence: 
            - 2
            - 5
            - 8
          movieTimings: 
            - '11:00'
            - '16:10'
            - '21:10'
      -   title: The Batman
          description: About Bat Man adventure
          runningTime: 95
          ticketPrice: 9
          specialCode: 0
          movieSequence: 
            - 3
            - 6
            - 9
          movieTimings: 
            - '12:50'
            - '17:50'
            - '23:00'       